#!/bin/bash
# E2B Sandbox Setup Script for workspace-alberta-metal_fabrication
# Generated by WorkspaceAlberta

set -e

echo "Setting up metal_fabrication environment..."

# Install Claude Code CLI
npm install -g @anthropic-ai/claude-code

# Install Python MCP dependencies
pip install mcp pandas openpyxl

# Copy MCP config to home directory
cp /workspace/.mcp.json ~/.mcp.json

# Install Node MCP server packages
npm install -g @modelcontextprotocol/server-filesystem
npm install -g @anthropic/mcp-server-brave-search

echo "Setup complete for metal_fabrication"
