"""API-key auth and Pro-tool gating for the hosted procurement server.

Design (see ``docs/pricing-and-subscription.md`` and the tooling roadmap):

- **Free tools stay open.** Search, details, deadlines, and the daily brief
  are unauthenticated marketing surface. Only ``PRO_TOOLS`` require a key.
- **Bearer keys.** Clients send ``Authorization: Bearer wa_live_...``. Keys
  are generated by :func:`generate_api_key`, and only their SHA-256 hash is
  stored (:func:`hash_api_key`) — a database leak never leaks usable keys.
- **Supabase is the primary validator.** The ``wa_subscribers`` table (kept
  in sync by the Stripe webhook in ``server_http.py``) is queried over
  PostgREST with the service-role key. A row with ``status='active'`` means
  the key is good.
- **Stripe metadata is the fallback validator.** If Supabase is not
  configured but ``STRIPE_SECRET_KEY`` is, the key hash is searched in
  Stripe customer metadata (``wa_key_hash``) and the customer's subscription
  status is checked live.
- **TTL cache.** Validation results are cached in memory for
  ``CACHE_TTL_SECONDS`` so steady-state traffic makes no upstream calls.
  Revocation therefore propagates within one TTL window.

The stdio adapter (``server.py``) never gates: a local single-user install
is the owner's own machine and own keys.

Environment variables:
    SUPABASE_URL               e.g. https://<ref>.supabase.co
    SUPABASE_SERVICE_ROLE_KEY  service-role secret (server-side only)
    STRIPE_SECRET_KEY          optional fallback validator
    WA_GATE_DISABLED           set 1 to disable gating entirely (dev)
"""

from __future__ import annotations

import hashlib
import json
import os
import secrets
import time
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen

KEY_PREFIX = "wa_live_"
CACHE_TTL_SECONDS = 300
# Unknown keys are cached too (to amortize lookups), so without a bound a
# flood of random wa_live_* keys would grow this dict without limit.
MAX_CACHE_ENTRIES = 4096

#: Tools that require an active subscription on the hosted server.
PRO_TOOLS = frozenset(
    {
        "process_bid_room",
        "analyze_contract_with_cohere",
        "watch_opportunity",
        "list_watchlist",
        "unwatch_opportunity",
        "bid_no_bid_scorecard",
    }
)

_cache: dict[str, tuple[float, dict[str, Any] | None]] = {}


class GateError(Exception):
    """Raised when a Pro tool is called without a valid subscription key.

    ``status_code`` maps cleanly onto HTTP: 401 (missing/invalid key),
    402 (key known but subscription not active), 503 (no validator
    configured).
    """

    def __init__(self, status_code: int, message: str) -> None:
        self.status_code = status_code
        super().__init__(message)


# ============== Key material ==============


def generate_api_key() -> str:
    """Return a new subscriber key. Shown once; only its hash is stored."""
    return KEY_PREFIX + secrets.token_urlsafe(32)


def hash_api_key(key: str) -> str:
    """SHA-256 hex digest of a key — the only form ever persisted."""
    return hashlib.sha256(key.strip().encode("utf-8")).hexdigest()


def extract_bearer_key(authorization_header: str | None) -> str:
    """Pull the key out of an ``Authorization: Bearer ...`` header value."""
    if not authorization_header:
        return ""
    parts = authorization_header.strip().split(None, 1)
    if len(parts) == 2 and parts[0].lower() == "bearer":
        return parts[1].strip()
    return ""


# ============== Configuration ==============


def supabase_config() -> tuple[str, str]:
    url = os.environ.get("SUPABASE_URL", "").strip().rstrip("/")
    key = (
        os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()
        or os.environ.get("SUPABASE_SECRET_KEY", "").strip()
    )
    return url, key

def stripe_secret_key() -> str:
    return os.environ.get("STRIPE_SECRET_KEY", "").strip()


def gate_enabled() -> bool:
    """The gate is active unless explicitly disabled or nothing can validate."""
    if os.environ.get("WA_GATE_DISABLED", "").lower() in {"1", "true", "yes"}:
        return False
    url, key = supabase_config()
    return bool(url and key) or bool(stripe_secret_key())


# ============== Validators ==============


def _supabase_lookup(key_hash: str) -> dict[str, Any] | None:
    """Fetch the subscriber row for a key hash, or None."""
    url, service_key = supabase_config()
    params = urlencode(
        {
            "key_hash": f"eq.{key_hash}",
            "select": "key_hash,stripe_customer_id,email,status,plan",
            "limit": "1",
        }
    )
    request = Request(
        f"{url}/rest/v1/wa_subscribers?{params}",
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Accept": "application/json",
        },
    )
    try:
        with urlopen(request, timeout=15) as response:
            rows = json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, json.JSONDecodeError) as exc:
        raise GateError(503, f"Subscriber lookup failed: {exc}") from exc
    return rows[0] if rows else None


def _stripe_lookup(key_hash: str) -> dict[str, Any] | None:
    """Fallback: find a Stripe customer by metadata wa_key_hash and check subs."""
    secret = stripe_secret_key()
    query = quote(f"metadata['wa_key_hash']:'{key_hash}'")
    request = Request(
        f"https://api.stripe.com/v1/customers/search?query={query}&limit=1",
        headers={"Authorization": f"Bearer {secret}"},
    )
    try:
        with urlopen(request, timeout=15) as response:
            body = json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, json.JSONDecodeError) as exc:
        raise GateError(503, f"Stripe lookup failed: {exc}") from exc

    customers = body.get("data", [])
    if not customers:
        return None
    customer = customers[0]

    sub_request = Request(
        f"https://api.stripe.com/v1/subscriptions?customer={customer['id']}&status=active&limit=1",
        headers={"Authorization": f"Bearer {secret}"},
    )
    try:
        with urlopen(sub_request, timeout=15) as response:
            subs = json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, json.JSONDecodeError) as exc:
        raise GateError(503, f"Stripe subscription check failed: {exc}") from exc

    active = bool(subs.get("data"))
    return {
        "key_hash": key_hash,
        "stripe_customer_id": customer["id"],
        "email": customer.get("email", ""),
        "status": "active" if active else "cancelled",
        "plan": "pro",
    }


def validate_key(key: str) -> dict[str, Any]:
    """Validate a raw API key, returning the subscriber record.

    Raises :class:`GateError` (401 unknown key, 402 inactive subscription,
    503 validator unavailable). Results — including "unknown" — are cached
    for ``CACHE_TTL_SECONDS``.
    """
    if not key or not key.startswith(KEY_PREFIX):
        raise GateError(401, "A WorkspaceAlberta Pro API key is required for this tool.")

    key_hash = hash_api_key(key)
    now = time.time()
    cached = _cache.get(key_hash)
    if cached and now - cached[0] < CACHE_TTL_SECONDS:
        record = cached[1]
    else:
        url, service_key = supabase_config()
        if url and service_key:
            record = _supabase_lookup(key_hash)
        elif stripe_secret_key():
            record = _stripe_lookup(key_hash)
        else:
            raise GateError(503, "Subscription validation is not configured on this server.")
        _cache_put(key_hash, record, now)

    if record is None:
        raise GateError(401, "Unknown API key. Check the key from your subscription email.")
    if record.get("status") != "active":
        raise GateError(
            402,
            "Your subscription is not active. Manage billing via Stripe or resubscribe at subscribe.html.",
        )
    return record


def check_tool_access(tool_name: str, authorization_header: str | None) -> dict[str, Any] | None:
    """Gate one tool call. Returns the subscriber record when authenticated.

    Rules:

    - Gate disabled (dev / no validator configured): always anonymous.
    - A valid key is honoured on *any* tool, so a subscriber's profile and
      watchlist are tenant-scoped even on free tools.
    - Pro tools without a valid key raise :class:`GateError`.
    - Free tools with a bad key degrade to anonymous rather than failing.
    """
    if not gate_enabled():
        return None

    key = extract_bearer_key(authorization_header)
    is_pro = tool_name in PRO_TOOLS

    if not key:
        if is_pro:
            raise GateError(401, "A WorkspaceAlberta Pro API key is required for this tool.")
        return None

    try:
        return validate_key(key)
    except GateError:
        if is_pro:
            raise
        return None


def _cache_put(key_hash: str, record: dict[str, Any] | None, now: float) -> None:
    """Insert a validation result, keeping the cache bounded."""
    if len(_cache) >= MAX_CACHE_ENTRIES:
        expired = [k for k, (ts, _) in _cache.items() if now - ts >= CACHE_TTL_SECONDS]
        for stale in expired:
            _cache.pop(stale, None)
        if len(_cache) >= MAX_CACHE_ENTRIES:
            # Still full of fresh entries (e.g. a key-guessing flood): drop
            # the oldest half rather than refusing to cache real subscribers.
            for stale in sorted(_cache, key=lambda k: _cache[k][0])[: MAX_CACHE_ENTRIES // 2]:
                _cache.pop(stale, None)
    _cache[key_hash] = (now, record)


def clear_cache() -> None:
    """Drop all cached validations (used by tests and the webhook)."""
    _cache.clear()
