# This is a config for E2B sandbox template.
# You can use template ID (f0tgbn7bxm8pjxo4huo4) or template name (canadabuys-showcase) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("canadabuys-showcase") # Sync sandbox
# sandbox = await AsyncSandbox.create("canadabuys-showcase") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('canadabuys-showcase')

team_id = "3b71001e-263c-47e6-95aa-25f9e4cd5e0d"
dockerfile = "Dockerfile"
template_name = "canadabuys-showcase"
template_id = "f0tgbn7bxm8pjxo4huo4"
