from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from generator.profiles import build_profile_mcp_json, get_profile_info, list_profiles


@dataclass(frozen=True)
class TemplateConfig:
    profile_name: str
    template_name: str
    mcp_config: dict[str, object]
    description: str


TEMPLATES_DIR = Path(__file__).parent / "templates"
MANIFEST_PATH = TEMPLATES_DIR / "manifest.json"


def _now_iso() -> str:
    return datetime.utcnow().isoformat() + "Z"


def generate_template_config(profile: str) -> TemplateConfig:
    info = get_profile_info(profile)
    mcp_config = build_profile_mcp_json(profile)

    return TemplateConfig(
        profile_name=profile,
        template_name=f"workspace-alberta-{profile}",
        mcp_config=mcp_config,
        description=str(info["description"]),
    )


def write_template_files(config: TemplateConfig) -> Path:
    template_dir = TEMPLATES_DIR / config.profile_name
    template_dir.mkdir(parents=True, exist_ok=True)

    mcp_path = template_dir / ".mcp.json"
    mcp_path.write_text(json.dumps(config.mcp_config, indent=2), encoding="utf-8")

    setup_script = f"""#!/bin/bash
# E2B Sandbox Setup Script for {config.template_name}
# Generated by WorkspaceAlberta

set -e

echo "Setting up {config.profile_name} environment..."

# Install Claude Code CLI
npm install -g @anthropic-ai/claude-code

# Install Python MCP dependencies
pip install mcp pandas openpyxl

# Copy MCP config to home directory
cp /workspace/.mcp.json ~/.mcp.json

# Install Node MCP server packages
npm install -g @modelcontextprotocol/server-filesystem
npm install -g @anthropic/mcp-server-brave-search

echo "Setup complete for {config.profile_name}"
"""

    (template_dir / "setup.sh").write_text(setup_script, encoding="utf-8")

    dockerfile = f"""# E2B Template: {config.template_name}
# Profile: {config.profile_name}
# Description: {config.description}

FROM e2b/code-interpreter:latest

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    python3-pip \\
    && rm -rf /var/lib/apt/lists/*

# Install Node.js MCP servers
RUN npm install -g @anthropic-ai/claude-code \\
    @modelcontextprotocol/server-filesystem \\
    @anthropic/mcp-server-brave-search

# Install Python dependencies
RUN pip3 install mcp pandas openpyxl

# Copy MCP configuration
COPY .mcp.json /root/.mcp.json

# Copy setup script
COPY setup.sh /workspace/setup.sh
RUN chmod +x /workspace/setup.sh

# Set working directory
WORKDIR /workspace

# Default command
CMD ["bash"]
"""

    (template_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")

    e2b_toml = f"""# E2B template configuration for {config.template_name}

[template]
name = "{config.template_name}"
description = "{config.description}"

[build]
dockerfile = "Dockerfile"

[runtime]
# Allocate resources for agent workloads
cpu_count = 2
memory_mb = 4096
"""

    (template_dir / "e2b.toml").write_text(e2b_toml, encoding="utf-8")

    print(f"  Created template files in: {template_dir}")

    return template_dir


def load_manifest() -> dict[str, object]:
    if MANIFEST_PATH.exists():
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

    return {
        "templates": {},
        "lastUpdated": _now_iso(),
    }


def save_manifest(manifest: dict[str, object]) -> None:
    manifest["lastUpdated"] = _now_iso()
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def build_template(profile: str) -> None:
    print(f"\nBuilding template for: {profile}")

    config = generate_template_config(profile)
    template_dir = write_template_files(config)

    manifest = load_manifest()
    templates = manifest.setdefault("templates", {})
    templates[profile] = {
        "templateId": f"pending-{profile}",
        "profileName": profile,
        "description": config.description,
        "createdAt": _now_iso(),
    }
    save_manifest(manifest)

    print("  Template ready. To deploy to E2B:")
    print(f"    cd {template_dir}")
    print("    e2b template build")


def build_all_templates() -> None:
    print("Building E2B templates for all profiles...\n")
    profiles = list_profiles()

    for profile in profiles:
        build_template(profile)

    print(f"\nGenerated {len(profiles)} templates in: {TEMPLATES_DIR}")
    print("\nNext steps:")
    print("  1. Install E2B CLI: npm install -g @e2b/cli")
    print("  2. Login to E2B: e2b login")
    print("  3. Build each template: cd e2b/templates/<profile> && e2b template build")


def list_all_profiles() -> None:
    print("\nAvailable Profiles for E2B Templates:\n")
    for profile in list_profiles():
        info = get_profile_info(profile)
        tools = info["tools"]
        summary = ", ".join(tools[:5])
        if len(tools) > 5:
            summary += "..."
        print(f"  {profile}")
        print(f"    {info['description']}")
        print(f"    Tools ({info['tool_count']}): {summary}\n")


def generate_orchestrator_code() -> None:
    manifest = load_manifest()
    template_ids = {
        profile: data["templateId"]
        for profile, data in manifest.get("templates", {}).items()
    }

    code = f"""\"\"\"
Auto-generated Child Agent Spawner

This module provides functions to spawn specialized child agents
in E2B sandboxes using pre-built templates.

Generated: {_now_iso()}
\"\"\"

from __future__ import annotations

from typing import Dict, List, Optional

try:
    from e2b import Sandbox
except ImportError as exc:  # pragma: no cover - optional runtime dependency
    Sandbox = None
    _IMPORT_ERROR = exc
else:
    _IMPORT_ERROR = None

TEMPLATE_IDS: Dict[str, str] = {json.dumps(template_ids, indent=2)}


class TemplateNotDeployedError(RuntimeError):
    \"\"\"Raised when a template has not been deployed to E2B.\"\"\"


def _require_sdk() -> None:
    if Sandbox is None:  # pragma: no cover
        raise ImportError(
            "Install the E2B Python SDK: pip install e2b"
        ) from _IMPORT_ERROR


def spawn_child_agent(
    profile: str,
    task: str,
    timeout_minutes: int = 10,
) -> Dict[str, object]:
    _require_sdk()
    template_id = TEMPLATE_IDS.get(profile)
    if not template_id or template_id.startswith("pending-"):
        raise TemplateNotDeployedError(f"Template not deployed for profile: {{profile}}")

    timeout_seconds = timeout_minutes * 60

    sandbox = Sandbox.create(template=template_id, timeout=timeout_seconds)
    try:
        escaped_task = task.replace('"', '\\"')
        result = sandbox.commands.run(
            f'claude-code --print "{{escaped_task}}"',
            timeout=timeout_seconds,
        )
        return {{
            "sandbox_id": getattr(sandbox, "sandbox_id", None),
            "profile": profile,
            "result": getattr(result, "stdout", ""),
            "exit_code": getattr(result, "exit_code", 0),
        }}
    finally:
        sandbox.close()


def list_profiles() -> List[str]:
    return list(TEMPLATE_IDS.keys())
"""

    output_path = Path(__file__).parent / "orchestrator.py"
    output_path.write_text(code, encoding="utf-8")
    print(f"Generated orchestrator code: {output_path}")


def main(args: list[str]) -> int:
    if not args:
        print(
            """
E2B Template Builder for WorkspaceAlberta

Usage:
  python -m e2b.build_templates <command> [args]

Commands:
  list                    List available profiles
  build <profile>         Build template for a specific profile
  build-all               Build templates for all profiles
  generate-orchestrator   Generate Python code for spawning agents

Examples:
  python -m e2b.build_templates list
  python -m e2b.build_templates build steel_fabrication
  python -m e2b.build_templates build-all
""",
            file=sys.stderr,
        )
        return 1

    command = args[0]

    if command == "build-all":
        build_all_templates()
        return 0

    if command == "build":
        if len(args) < 2:
            print("Usage: build_templates.py build <profile_name>", file=sys.stderr)
            print("Run 'build_templates.py list' to see available profiles.", file=sys.stderr)
            return 1
        build_template(args[1])
        return 0

    if command == "list":
        list_all_profiles()
        return 0

    if command == "generate-orchestrator":
        generate_orchestrator_code()
        return 0

    print(f"Unknown command: {command}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
